RecipeHub.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using RecipeHub.Models;

namespace RecipeHub.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RecipeHub.Web/Controllers/RecipeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RecipeHub.Data.Repository.Interfaces;
using RecipeHub.Data.Models;
using RecipeHub.Web.ViewModels.Recipe;
using RecipeHub.Services.Data.Interfaces;
using System.Threading.Tasks;

namespace RecipeHub.Web.Controllers
{
    public class RecipeController : Controller
    {
        private readonly IRecipeService recipeService;
        
        public RecipeController(IRecipeService _recipeService)
        {
           recipeService = _recipeService;
        }
        public async Task<IActionResult> All(string searchText, string[]checkedCategories)
        {

            var categories = await recipeService.GetCategoryNamesAsync();


            var list = await recipeService.GetAllRecipesAsync(searchText,checkedCategories);
           

            var model = new RecipeAndCategoryModel()
            {
                Recipes = list,
                CategoryNames = categories
            };

            ViewData["SearchText"] = searchText;

            return View(model);
        }
        [HttpGet]
        public IActionResult Add()
        {
            AddRecipeModel model = new AddRecipeModel();
           

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult>Add(AddRecipeModel model)
        {
            
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var RecipeId = await recipeService.AddRecipeAsync(model);

            return RedirectToAction("AddIngredients", new {id=RecipeId});
        }
        [HttpGet]
        public IActionResult AddSteps()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddSteps(string id,List<string> steps)
        {
            Guid GuidId=Guid.Parse(id);

            await recipeService.AddStepsAsync(GuidId, steps);

            return RedirectToAction("AddCategory", new { id = GuidId });
        }
        [HttpGet]
        public IActionResult AddIngredients()
        {
            var model = new IngridientViewModel();
            model.Units = recipeService.GetUnitTypes();

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AddIngredients(string id, List<IngridientViewModel> Ingredients)
        {
            Guid GuidId = Guid.Parse(id);

            await recipeService.AddIngredientsAsync(GuidId, Ingredients);  

            return RedirectToAction("AddSteps", new { id = GuidId });
        }
        public async Task<IActionResult>Details(string id)
        {
            Guid GuidId = Guid.Parse(id);

            var model=await recipeService.GetDetailsModelAsync(GuidId);

            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> AddCategory(string id)
        {
            Guid GuidId = Guid.Parse(id);
            var dictionary = await recipeService.GetCategoryForRecipeAsync(GuidId);


            return View(dictionary);
        }
        [HttpPost]
        public async Task<IActionResult> AddCategory(string id,string[] checkedCategories)
        {
            Guid GuidId = Guid.Parse(id);

           await recipeService.AddCategoriesAsync(GuidId, checkedCategories);

            return RedirectToAction("All");
        }
    }
}

RecipeHub.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container mt-5">

    
    <div class="jumbotron text-center bg-light p-5 rounded shadow">
        <h1 class="display-4">Welcome to RecipeHub 🍽️</h1>
        <p class="lead">Discover, cook, and enjoy delicious recipes from around the world.</p>
        <a class="btn btn-success btn-lg mt-3" asp-controller="Recipe" asp-action="All" role="button">Browse Recipes</a>
    </div>

   
    <div class="row mt-5">
        <div class="col-md-6">
            <img src="~/images/cooking.jpg" class="img-fluid rounded shadow-sm" alt="Cooking">
        </div>
        <div class="col-md-6 d-flex align-items-center">
            <div>
                <h2>What's Cooking?</h2>
                <p>
                    Whether you're a seasoned chef or just getting started, RecipeHub has something for everyone.
                    Add your own creations.
                </p>
                <a asp-controller="Recipe" asp-action="Add" class="btn btn-outline-primary">Add Your Own Recipe</a>
            </div>
        </div>
    </div>

</div>

RecipeHub.Web/Views/Recipe/Add.cshtml
@using RecipeHub.Web.ViewModels.Recipe
@model AddRecipeModel
<hr />

<form asp-controller="Recipe" asp-action="Add" method="post" enctype="multipart/form-data">
    <div>
        <label style="font-size:20px;">Title</label>
        <input asp-for="Title" style="font-size:20px; padding:5px; margin:20px; width:400px;" />
    </div>
    <div style="display:flex; align-items:center; gap:10px;">
        <label class="big-text">Upload Image</label>
        <input asp-for="ImageFile" type="file" style="height:40px; font-size:20px;" />
    </div>

    <button type="submit" style="font-size:16px; padding:8px 15px;">Save</button>
</form>



@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

RecipeHub.Web/Views/Recipe/AddCategory.cshtml
@model IDictionary<string,bool>


<form asp-action="AddCategory" method="post">
    <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 g-3">
        @foreach (var category in Model)
        {
            <div class="col">
                <label class="category-tile">
                    <input type="checkbox"
                           name="checkedCategories"
                           value="@category.Key"
                           class="category-checkbox" @(category.Value ? "checked" : "") />
                    <span class="category-label">@category.Key</span>
                </label>
            </div>
        }
    </div>

    <button type="submit" class="btn btn-primary mt-3">Choose</button>
</form>

RecipeHub.Web/Views/Recipe/AddIngredients.cshtml
@using RecipeHub.Web.ViewModels.Recipe
@model IngridientViewModel

<h2>Add Ingredients for your recipe</h2>



<form method="post" asp-action="AddIngredients">
    <div id="ingredientContainer">
        <div class="form-group d-flex gap-2 mb-2">
            <input name="Ingredients[0].Name" class="form-control" placeholder="Ingredient" />
            <input name="Ingredients[0].Quantity" class="form-control" placeholder="Quantity" />
            <select name="Ingredients[0].Unit" class="form-control" aria-required="true">
                <option disabled selected value="">Select Type....</option>
                @foreach (var unit in Model.Units!)
                {
                    <option value="@unit">@unit.ToString()</option>
                }
            </select>
        </div>
    </div>


    <button type="button" class="btn btn-outline-primary mb-2 p-2" onclick="addIngredient()">+</button>
    <br />
    <input class="btn btn-outline-primary mb-2 p-2 fw-bold" type="submit" value="Add Ingredients" />
</form>


<script>
    let index = 1;

    function addIngredient() {
        var container = document.getElementById('ingredientContainer');

        var div = document.createElement('div');
        div.className = "form-group d-flex gap-2 mb-2";

        var inputName = document.createElement('input');
        inputName.name = `Ingredients[${index}].Name`;
        inputName.className = 'form-control';
        inputName.placeholder = 'Ingredient';

        var inputQuantity = document.createElement('input');
        inputQuantity.name = `Ingredients[${index}].Quantity`;
        inputQuantity.className = 'form-control';
        inputQuantity.placeholder = 'Quantity';

         var selectUnit = document.createElement('select');
        selectUnit.name = `Ingredients[${index}].Unit`;
        selectUnit.className = 'form-control';

        var defaultOption = document.createElement('option');
        defaultOption.text = "Select Type...";
        defaultOption.value = "";
        defaultOption.disabled = true;
        defaultOption.selected = true;
        selectUnit.appendChild(defaultOption);

        var units = @Html.Raw(System.Text.Json.JsonSerializer.Serialize(Model.Units));
       
        units.forEach(u => {
            var opt = document.createElement('option');
            opt.value = u;
            opt.text = u;
            selectUnit.appendChild(opt);
        });

       
        div.appendChild(inputName);
        div.appendChild(inputQuantity);
        div.appendChild(selectUnit);
        container.appendChild(div);

        index++;


  
    }
</script>

RecipeHub.Web/Views/Recipe/AddSteps.cshtml
<h2>Add Recipe Steps</h2>


<form method="post" asp-action="AddSteps">
    <div id="stepsContainer">
        <div class="form-group">
            <input name="steps" class="form-control" aria-required="true" />
        </div>
    </div>
    <br /><br />
    <button type="button" class="btn btn-outline-primary mb-2 p-2" onclick="addStep()">+</button>
    <br />
    <input class="btn btn-outline-primary mb-2 p-2 fw-bold" type="submit" value="Add Steps" />
</form>

<script>
    function addStep() {
        var container = document.getElementById('stepsContainer');
        var input = document.createElement('input');
        input.name = 'Steps';
        input.className = 'form-control my-2';
        container.appendChild(input);
    }
</script>

RecipeHub.Web/Views/Recipe/All.cshtml
@using RecipeHub.Web.ViewModels.Recipe
@model RecipeAndCategoryModel
@{
    ViewBag.Title = "All Recipes";
}

<h2 class="text-center mt-4">Our Recipes</h2>

<form asp-action="All" method="get">
    <div class="form-actions no-color text-center">
        <p>
            <label>Find Recipe: <input class="p-2 rounded" type="text" name="searchText" value="@ViewData["SearchText"]" /></label>
            <a asp-action="All" class="text-end btn btn-secondary m-1 rounded">Back to Full List</a>
        </p>
    </div>
</form>
<div class="dropdown">
    <button class="btn btn-light dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        Select Category
    </button>
     <form asp-action="All" method="get">
    <ul class="dropdown-menu p-2" style="min-width: 200px;">
    @foreach(var category in Model.CategoryNames)
        {
           
            <li>
                <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="checkedCategories" value="@category" />
                        <label class="form-check-label">@category</label>
                </div>
            </li>
            
        }
       
    </ul>
        <button type="submit" class="btn btn-primary mt-3">Filter</button>
    </form>
</div>



<div class="container mt-4">
    <div class="row">
        @foreach (var recipe in Model.Recipes)
        {
            <div class="col-md-4 mb-4">
                <div class="card h-100 shadow-sm text-center">
                    <img src="@recipe.ImageUrl" class="card-img-top" alt="@recipe.Name" style="height: 250px; object-fit: cover;">
                    <div class="card-body">
                        <h5 class="card-title">@recipe.Name</h5>
                        <a asp-controller="Recipe" asp-action="Details" asp-route-id="@recipe.Id" class="btn btn-outline-primary mt-2">
                            View Recipe
                        </a>         
                    </div>
                </div>
            </div>
        }
    </div>
</div>

RecipeHub.Web/Views/Recipe/Details.cshtml
@using RecipeHub.Web.ViewModels.Recipe
@model DetailsViewModel

@{
    ViewData["Title"] = "Recipe Details";
}

<h2 class="text-center pb-4">@Model.Name</h2>


<div class="row mb-4 mt-4">
    
    <div class="col-md-6">
        <h4>Ingredients</h4>
        <ul>
            @foreach (var ingredient in Model.Ingredients)
            {
                <li style="font-size: 20px;">@ingredient.Name - @ingredient.Weight</li>
            }
        </ul>
    </div>

   
    <div class="col-md-6 d-flex align-items-start justify-content-center mb-xxl-3">
        <img src="@Model.ImageUrl" alt="@Model.Name" class="img-fluid rounded" style="max-height: 400px; width: 100%; object-fit: cover;" />
    </div>
</div>


<div >
    <h4 class="mb-xxl-5 text-center">Preparation Steps</h4>
    <ul class="list-unstyled text-start ">
        @for (int i = 0; i < Model.Steps.Count; i++)
        {
            <li style="font-size: 20px;">@(i + 1). @Model.Steps[i]</li>
        }
    </ul>
</div>

RecipeHub.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RecipeHub</title>
    <link rel="stylesheet" href="~/css/MySite.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RecipeHub.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                      
                    </ul>
                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

  
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>